package handlers

import (
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/ARCOOON/arx-ca/internal/api"
	"github.com/ARCOOON/arx-ca/internal/db"
	"github.com/ARCOOON/arx-ca/internal/models"
	"github.com/ARCOOON/arx-ca/internal/notifications"
)

var webhookEventLabels = map[string]struct {
	Label       string
	Description string
}{
	db.ActionSysStart:             {Label: "System Start", Description: "API server process started"},
	db.ActionSysConfigUpdate:      {Label: "Configuration Update", Description: "Server or CA configuration changed"},
	db.ActionAuthLoginSuccess:     {Label: "Login Success", Description: "Administrator authenticated successfully"},
	db.ActionAuthLoginFailed:      {Label: "Login Failed", Description: "Failed administrator authentication attempt"},
	db.ActionCertIssueNative:      {Label: "Native Certificate Issuance", Description: "Key and certificate generated by the CA"},
	db.ActionCertIssueCSR:         {Label: "CSR Certificate Issuance", Description: "Certificate signed from a submitted CSR"},
	db.ActionCertRevoke:           {Label: "Certificate Revocation", Description: "Certificate revocation requests"},
	db.ActionCertRenew:            {Label: "Certificate Renewal", Description: "Certificate renewal operations"},
	db.ActionEABGenerate:          {Label: "EAB Key Generated", Description: "ACME External Account Binding key minted"},
	db.ActionEABRevoke:            {Label: "EAB Key Revoked", Description: "ACME External Account Binding key revoked"},
	db.ActionSCEPChallengeRotated: {Label: "SCEP Challenge Rotated", Description: "SCEP static challenge password rotated"},
	db.ActionSSHUserCertIssue:     {Label: "SSH User Certificate", Description: "SSH user certificate issued"},
	db.ActionSSHHostCertIssue:     {Label: "SSH Host Certificate", Description: "SSH host certificate issued"},
	db.ActionWebhookCreated:       {Label: "Webhook Created", Description: "Outbound webhook endpoint registered"},
	db.ActionWebhookDeleted:       {Label: "Webhook Deleted", Description: "Outbound webhook endpoint removed"},
	db.ActionWebhookUpdated:       {Label: "Webhook Updated", Description: "Outbound webhook configuration changed"},
}

// WebhookHandler serves webhook management endpoints.
type WebhookHandler struct {
	store      *db.WebhookStore
	dispatcher *notifications.Dispatcher
}

// NewWebhookHandler constructs a WebhookHandler.
func NewWebhookHandler(store *db.WebhookStore, dispatcher *notifications.Dispatcher) *WebhookHandler {
	return &WebhookHandler{store: store, dispatcher: dispatcher}
}

// List handles GET /api/v1/webhooks.
func (h *WebhookHandler) List() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			api.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}
		if h.store == nil {
			api.WriteError(w, http.StatusInternalServerError, "webhook store is unavailable")
			return
		}

		webhooks, err := h.store.List(r.Context())
		if err != nil {
			log.Printf("webhooks: list: %v", err)
			api.WriteError(w, http.StatusInternalServerError, "failed to list webhooks")
			return
		}

		resp := make([]models.WebhookResponse, 0, len(webhooks))
		for _, wh := range webhooks {
			resp = append(resp, toWebhookResponse(wh))
		}
		api.WriteSuccess(w, http.StatusOK, models.ListWebhooksResponse{Webhooks: resp})
	})
}

// Events handles GET /api/v1/webhooks/events.
func (h *WebhookHandler) Events() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet {
			api.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}

		events := make([]models.WebhookEventOption, 0, len(notifications.NotifiableActions))
		for _, action := range notifications.NotifiableActions {
			meta := webhookEventLabels[action]
			label := meta.Label
			if label == "" {
				label = action
			}
			events = append(events, models.WebhookEventOption{
				Action:      action,
				Label:       label,
				Description: meta.Description,
			})
		}
		api.WriteSuccess(w, http.StatusOK, models.WebhookEventsResponse{Events: events})
	})
}

// Create handles POST /api/v1/webhooks.
func (h *WebhookHandler) Create() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			api.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}
		if h.store == nil {
			api.WriteError(w, http.StatusInternalServerError, "webhook store is unavailable")
			return
		}

		var req models.CreateWebhookRequest
		if err := decodeJSONBody(w, r, &req); err != nil {
			api.WriteError(w, http.StatusBadRequest, err.Error())
			return
		}

		recordAuditAction(r, db.ActionWebhookCreated)
		if ac := auditFromRequest(r); ac != nil {
			ac.PutMetadata("webhook_name", strings.TrimSpace(req.Name))
		}

		wh, err := h.validateAndCreate(r, req)
		if err != nil {
			api.WriteError(w, http.StatusBadRequest, err.Error())
			return
		}

		created, err := h.store.Create(r.Context(), wh)
		if err != nil {
			log.Printf("webhooks: create: %v", err)
			api.WriteError(w, http.StatusInternalServerError, "failed to create webhook")
			return
		}

		api.WriteSuccess(w, http.StatusCreated, toWebhookResponse(created))
	})
}

// Update handles PUT /api/v1/webhooks/{id}.
func (h *WebhookHandler) Update() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPut {
			api.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}
		if h.store == nil {
			api.WriteError(w, http.StatusInternalServerError, "webhook store is unavailable")
			return
		}

		id := strings.TrimSpace(r.PathValue("id"))
		if id == "" {
			api.WriteError(w, http.StatusBadRequest, "webhook id is required")
			return
		}

		var req models.UpdateWebhookRequest
		if err := decodeJSONBody(w, r, &req); err != nil {
			api.WriteError(w, http.StatusBadRequest, err.Error())
			return
		}

		recordAuditAction(r, db.ActionWebhookUpdated)
		if ac := auditFromRequest(r); ac != nil {
			ac.PutMetadata("webhook_id", id)
		}

		wh, err := h.validateAndUpdate(id, req)
		if err != nil {
			api.WriteError(w, http.StatusBadRequest, err.Error())
			return
		}

		updated, err := h.store.Update(r.Context(), wh)
		if err != nil {
			if strings.Contains(err.Error(), "not found") {
				api.WriteError(w, http.StatusNotFound, "webhook not found")
				return
			}
			log.Printf("webhooks: update: %v", err)
			api.WriteError(w, http.StatusInternalServerError, "failed to update webhook")
			return
		}

		api.WriteSuccess(w, http.StatusOK, toWebhookResponse(updated))
	})
}

// Delete handles DELETE /api/v1/webhooks/{id}.
func (h *WebhookHandler) Delete() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodDelete {
			api.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}
		if h.store == nil {
			api.WriteError(w, http.StatusInternalServerError, "webhook store is unavailable")
			return
		}

		id := strings.TrimSpace(r.PathValue("id"))
		if id == "" {
			api.WriteError(w, http.StatusBadRequest, "webhook id is required")
			return
		}

		recordAuditAction(r, db.ActionWebhookDeleted)
		if ac := auditFromRequest(r); ac != nil {
			ac.PutMetadata("webhook_id", id)
		}

		if err := h.store.Delete(r.Context(), id); err != nil {
			if strings.Contains(err.Error(), "not found") {
				api.WriteError(w, http.StatusNotFound, "webhook not found")
				return
			}
			log.Printf("webhooks: delete: %v", err)
			api.WriteError(w, http.StatusInternalServerError, "failed to delete webhook")
			return
		}

		api.WriteSuccess(w, http.StatusOK, map[string]string{"deleted": id})
	})
}

// Test handles POST /api/v1/webhooks/{id}/test.
func (h *WebhookHandler) Test() http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodPost {
			api.WriteError(w, http.StatusMethodNotAllowed, "method not allowed")
			return
		}
		if h.store == nil || h.dispatcher == nil {
			api.WriteError(w, http.StatusInternalServerError, "webhook engine is unavailable")
			return
		}

		id := strings.TrimSpace(r.PathValue("id"))
		if id == "" {
			api.WriteError(w, http.StatusBadRequest, "webhook id is required")
			return
		}

		recordAuditAction(r, "WEBHOOK_TEST")

		webhook, err := h.store.GetByID(r.Context(), id)
		if err != nil {
			if strings.Contains(err.Error(), "not found") {
				api.WriteError(w, http.StatusNotFound, "webhook not found")
				return
			}
			log.Printf("webhooks: test lookup: %v", err)
			api.WriteError(w, http.StatusInternalServerError, "failed to load webhook")
			return
		}

		result := h.dispatcher.DispatchTest(r.Context(), webhook)
		resp := models.WebhookTestResponse{
			Success:    result.Error == "" && result.StatusCode >= 200 && result.StatusCode < 300,
			StatusCode: result.StatusCode,
			LatencyMS:  result.Latency.Milliseconds(),
			Error:      result.Error,
		}
		if !resp.Success && resp.Error == "" {
			resp.Error = "unexpected response status"
		}

		status := http.StatusOK
		if !resp.Success {
			status = http.StatusBadGateway
		}
		api.WriteSuccess(w, status, resp)
	})
}

func (h *WebhookHandler) validateAndCreate(_ *http.Request, req models.CreateWebhookRequest) (db.Webhook, error) {
	url := strings.TrimSpace(req.URL)
	name := strings.TrimSpace(req.Name)
	if url == "" {
		return db.Webhook{}, errValidation("url is required")
	}
	if name == "" {
		return db.Webhook{}, errValidation("name is required")
	}
	if !strings.HasPrefix(url, "http://") && !strings.HasPrefix(url, "https://") {
		return db.Webhook{}, errValidation("url must use http or https")
	}

	active := true
	if req.Active != nil {
		active = *req.Active
	}

	events := notifications.NormalizeSubscribedEvents(req.SubscribedEvents)
	if len(events) == 0 {
		return db.Webhook{}, errValidation("at least one subscribed event is required")
	}

	return db.Webhook{
		URL:              url,
		Name:             name,
		SecretToken:      strings.TrimSpace(req.SecretToken),
		Active:           active,
		SubscribedEvents: events,
	}, nil
}

func (h *WebhookHandler) validateAndUpdate(id string, req models.UpdateWebhookRequest) (db.Webhook, error) {
	url := strings.TrimSpace(req.URL)
	name := strings.TrimSpace(req.Name)
	if url == "" {
		return db.Webhook{}, errValidation("url is required")
	}
	if name == "" {
		return db.Webhook{}, errValidation("name is required")
	}
	if !strings.HasPrefix(url, "http://") && !strings.HasPrefix(url, "https://") {
		return db.Webhook{}, errValidation("url must use http or https")
	}

	events := notifications.NormalizeSubscribedEvents(req.SubscribedEvents)
	if len(events) == 0 {
		return db.Webhook{}, errValidation("at least one subscribed event is required")
	}

	return db.Webhook{
		ID:               id,
		URL:              url,
		Name:             name,
		SecretToken:      strings.TrimSpace(req.SecretToken),
		Active:           req.Active,
		SubscribedEvents: events,
	}, nil
}

func toWebhookResponse(wh db.Webhook) models.WebhookResponse {
	return models.WebhookResponse{
		ID:               wh.ID,
		URL:              wh.URL,
		Name:             wh.Name,
		Active:           wh.Active,
		SubscribedEvents: wh.SubscribedEvents,
		HasSecretToken:   strings.TrimSpace(wh.SecretToken) != "",
		CreatedAt:        wh.CreatedAt.UTC().Format(time.RFC3339Nano),
		UpdatedAt:        wh.UpdatedAt.UTC().Format(time.RFC3339Nano),
	}
}

type validationError string

func (e validationError) Error() string { return string(e) }

func errValidation(message string) error {
	return validationError(message)
}
